apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: windripper-webhook
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    windripper:
      port: "12000"
      endpoint: /windripper
      method: POST
