apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: windripper-sensor
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
  - name: payload
    eventSourceName: windripper-webhook
    eventName: windripper
  triggers:
  - template:
      name: windripper
      k8s:
        group: ""
        version: v1
        resource: pods
        operation: create
        source:
          resource:
            apiVersion: v1
            kind: Pod
            metadata:
              generateName: windripper-
              labels:
                app: windripper
            spec:
              containers:
              - name: publish
                image: core.harbor.domain/digitalforge/windripper:0.1.7
                command: ["python"]
                env:
                - name: SQLHOST
                  value: postgres-postgresql.windstorm:5432
                - name: WINDSTORMHOST
                  value: http://windstorm-webhook-eventsource-svc.argo-events:12000/windstorm
                args:
                - "main.py"
                - ""
                - ""
                - ""
              restartPolicy: Never
        parameters:
          - src:
              dependencyName: payload
              dataKey: body.type
            dest: spec.containers.0.args.1
          - src:
              dependencyName: payload
              dataKey: body.event_data.resources.0.resource_url
            dest: spec.containers.0.args.2
          - src:
              dependencyName: payload
              dataKey: body.event_data.resources.0.digest
            dest: spec.containers.0.args.3
