apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: windripper-sensor
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
  - name: payload
    eventSourceName: windripper-webhook
    eventName: windripper
  triggers:
  - template:
      name: windripper
      k8s:
        group: ""
        version: v1
        resource: pods
        operation: create
        source:
          resource:
            apiVersion: v1
            kind: Pod
            metadata:
              generateName: windripper-
              labels:
                app: windripper
            spec:
              containers:
              - name: publish
                image: docker.io/westfallio/windripper:v0.2.4
                command: ["python"]
                env:
                - name: SQLHOST
                  value: postgres-postgresql.windstorm:5432
                - name: HARBORHOST
                  value: http://harbor-core.harbor/api/v2.0
                - name: WINDSTORMHOST
                  value: http://windstorm-webhook-eventsource-svc.argo-events:12000/windstorm
                - name: DBUSER  # name of env var
                  valueFrom:
                    secretKeyRef:
                      name: dbparams     # name of an existing k8s secret
                      key: username     # 'key' subcomponent of the secret
                - name: DBPASS  # name of env var
                  valueFrom:
                    secretKeyRef:
                      name: dbparams     # name of an existing k8s secret
                      key: password     # 'key' subcomponent of the secret
                - name: DBTABLE  # name of env var
                  valueFrom:
                    secretKeyRef:
                      name: dbparams     # name of an existing k8s secret
                      key: table     # 'key' subcomponent of the secret
                - name: HARBORUSER  # name of env var
                  valueFrom:
                    secretKeyRef:
                      name: harborparams     # name of an existing k8s secret
                      key: username     # 'key' subcomponent of the secret
                - name: HARBORPASS  # name of env var
                  valueFrom:
                    secretKeyRef:
                      name: harborparams     # name of an existing k8s secret
                      key: password     # 'key' subcomponent of the secret
                args:
                - "src/main.py"
                - ""
                - ""
                - ""
              restartPolicy: Never
        parameters:
          - src:
              dependencyName: payload
              dataKey: body.type
            dest: spec.containers.0.args.1
          - src:
              dependencyName: payload
              dataKey: body.event_data.resources.0.resource_url
            dest: spec.containers.0.args.2
          - src:
              dependencyName: payload
              dataKey: body.event_data.resources.0.digest
            dest: spec.containers.0.args.3
